baseURL = "https://aidinbii.netlify.app"
languageCode = "en"
title = "Aidin Biibosunov"
theme = "aether"
#googleAnalytics = "Your google analytics tracking ID - optional"
#disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "aidinbii"
description = "Personal blog"
github = "https://github.com/aidinbii"
homeimg = "img/footer-hex.png"
bgimg = "img/seamless-background-image-tile.jpg"
rssinmenu = true

[markup]
  [markup.highlight]
    style = "igor"
