baseURL = "https://aidinbii.netlify.app"
languageCode = "en-us"
title = "Aidin Biibosunov"
theme = "ezhil"

copyright = "© Copyright notice"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
# googleAnalytics = "G-1GQSC4QRCT"
# Your Disqus sortname. for enabling comments on the site
disqusShortname = "aidinbii"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Welcome to my blog"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts", "lists"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/favicon-32x32.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    # mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/my_custom.css"
    # Custom CSS added to dark mode style.
    #customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    #customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]
    customJS = ["js/index.js", "js/placeholders.js",
    "https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js"]


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/blog"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 4

[[menu.main]]
name = "Lists"
url = "/lists"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aidinbii"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/aidinbii"

# Enable tags.
[taxonomies]
   tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# enableGitInfo = true

# [frontmatter]
#   date = ['date', 'publishDate', 'lastmod']
#   expiryDate = ['expiryDate']
#   lastmod = [':git', 'lastmod', 'date', 'publishDate']
#   publishDate = ['publishDate', 'date']
